name: Backend-Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create backend.env from Secrets
        run: |
          echo "MYSQL_HOST=mysql" >> backend.env
          echo "MYSQL_PORT=3306" >> backend.env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> backend.env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> backend.env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> backend.env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> backend.env
          echo "PORT=${{ secrets.BACKEND_PORT }}" >> backend.env

      - name: Create frontend.env from Secrets
        run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> frontend.env
          echo "REACT_APP_API_TIMEOUT=${{ secrets.REACT_APP_API_TIMEOUT }}" >> frontend.env

      - name: Build Docker Compose
        run: docker compose build

      - name: Stop Running Containers
        run: docker compose down

      - name: Start Containers
        run: docker compose up -d
